profile=fast
audio-display=no

slang=en,eng,English
alang=ja,jp,jpn,jap,Japanese,en,eng,English
replaygain=track
replaygain-preamp=0
replaygain-clip=no
replaygain-fallback=0

window-maximized=yes
input-terminal=yes
autofit-larger=1280x720

vo=gpu,sdl,null
hwdec=auto
keep-open=yes
autocreate-playlist=same
force-seekable=yes
