[[mgr.prepend_keymap]]
on = ["."]
run = "hidden toggle"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on = ["e"]
run = "shell '${EDITOR:-nvim} %s || { echo \"Editor failed with exit code $?\"; read -p \"Press Enter to continue...\"; }' --block"
desc = "Open with editor"

[[mgr.prepend_keymap]]
on = ["E"]
run = "open --interactive"
desc = "Extract/Open interactive"


