[[mgr.prepend_keymap]]
on = ["."]
run = "hidden toggle"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on = ["v"]
run = [ "escape", "toggle_all" ]
desc = "Toggle select all files"

[[mgr.prepend_keymap]]
on = ["e"]
run = "shell '${EDITOR:-nvim} %s || { echo \"Editor failed with exit code $?\"; read -p \"Press Enter to continue...\"; }' --block"
desc = "Open with editor"

[[mgr.prepend_keymap]]
on = ["O"]
run = "open --interactive"
desc = "Open interactive"

[[mgr.prepend_keymap]]
on = ["R"]
run = "shell '$HOME/.local/scripts/py/yazi-rename.py %S 2>&1' --block"
desc = "Bulk rename in editor"

[[mgr.prepend_keymap]]
on = ["t", "f"]
run = "shell '$HOME/.local/scripts/py/yazi-translate.py --rename %S 2>&1' --block"
desc = "Translate filename(s) to English"

[[mgr.prepend_keymap]]
on = ["t", "c"]
run = "shell '$HOME/.local/scripts/py/yazi-translate.py --quiet --file %S 2>&1' --block"
desc = "Translate file content(s) to English"

[[mgr.prepend_keymap]]
on = ["x"]
run = "shell '$HOME/.local/scripts/py/yazi-extract.py %S 2>&1; echo; read -p \"Press Enter to continue...\"' --block"
desc = "Extract archive(s)"

[[mgr.prepend_keymap]]
on = ["C"]
run = "shell '$HOME/.local/scripts/py/yazi-ffmpeg-concat.py %S 2>&1; echo; read -p \"Press Enter to continue...\"' --block"
desc = "Concat media files"

[[mgr.prepend_keymap]]
on = ["T"]
run = "shell '$HOME/.local/scripts/py/yazi-ffmpeg-transcode.py %S 2>&1; echo; read -p \"Press Enter to continue...\"' --block"
desc = "Transcode media file(s)"
