[tasks]
suppress_preload = true

[opener]
edit = [
  { run = 'nvim "%s"', block = true, for = "windows" },
  { run = '${EDITOR:-nvim} "%s"', block = true, for = "unix" },
]
play = [
  { run = 'mpv %s', orphan = true, desc = "Play with mpv", for = "unix" },
  { run = 'mpv %s', orphan = true, desc = "Play with mpv", for = "windows" },
]
open = [
  { run = 'explorer "%s"', orphan = true, desc = "Open", for = "windows" },
  { run = 'xdg-open "%s"', orphan = true, desc = "Open", for = "linux" },
  { run = 'open "%s"', orphan = true, desc = "Open", for = "macos" },
]

[open]
rules = [
  { mime = "text/*", use = [ "edit" ] },
  { mime = "image/*", use = [ "open" ] },
  { mime = "{audio,video}/*", use = [ "play", "open" ] },
  { mime = "*", use = [ "edit", "open" ] },
]
