[opener]
edit = [
  { run = 'nvim "%s"', block = true, for = "windows" },
  { run = '${EDITOR:-nvim} "%s"', block = true, for = "unix" },
]
open = [
  { run = 'explorer "%s"', orphan = true, desc = "Open", for = "windows" },
  { run = 'xdg-open "%s"', orphan = true, desc = "Open", for = "linux" },
  { run = 'open "%s"', orphan = true, desc = "Open", for = "macos" },
]
extract = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-extract.py %s', block = true, desc = "Extract to...", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-extract.py" %s', block = true, desc = "Extract to...", for = "windows" },
]
compress_7z = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-compress.py 7z %s', block = true, desc = "Compress to 7z", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-compress.py" 7z %s', block = true, desc = "Compress to 7z", for = "windows" },
]
compress_zip = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-compress.py zip %s', block = true, desc = "Compress to Zip", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-compress.py" zip %s', block = true, desc = "Compress to Zip", for = "windows" },
]
concat_media = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-ffmpeg-concat.py %s', block = true, desc = "Concat media", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-ffmpeg-concat.py" %s', block = true, desc = "Concat media", for = "windows" },
]
transcode_media = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-ffmpeg-transcode.py %s', block = true, desc = "Transcode media", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-ffmpeg-transcode.py" %s', block = true, desc = "Transcode media", for = "windows" },
]

[open]
rules = [
  { mime = "*", use = [
    "open",
    "edit",
    "compress_7z",
    "compress_zip",
  ] },
]

[[plugin.prepend_fetchers]]
id    = "mime"
group = "mime"
url   = "local://*"
run   = "mime-broad"
prio  = "high"

[[plugin.prepend_fetchers]]
id    = "mime"
group = "mime"
url   = "remote://*"
run   = "mime-broad"
prio  = "high"
