[tasks]
suppress_preload = true

[opener]
edit = [
  { run = 'nvim "%s"', block = true, for = "windows" },
  { run = 'nvim %s1', block = true, for = "unix" },
]
play = [
  { run = 'mpv %s', orphan = true, desc = "Play with mpv", for = "unix" },
  { run = 'mpv %s', orphan = true, desc = "Play with mpv", for = "windows" },
]
open = [
  { run = 'explorer "%s"', orphan = true, desc = "Open", for = "windows" },
  { run = 'xdg-open %s', orphan = true, desc = "Open", for = "linux" },
  { run = 'open %s', orphan = true, desc = "Open", for = "macos" },
]
extract = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-extract.py %s', block = true, desc = "Extract", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-extract.py" %s', block = true, desc = "Extract", for = "windows" },
]
compress_7z = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-compress.py 7z %s', block = true, desc = "Comp 7z", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-compress.py" 7z %s', block = true, desc = "Comp 7z", for = "windows" },
]
compress_zip = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-compress.py zip %s', block = true, desc = "Comp zip", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-compress.py" zip %s', block = true, desc = "Comp zip", for = "windows" },
]
concat_media = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-ffmpeg-concat.py %s', block = true, desc = "Concat", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-ffmpeg-concat.py" %s', block = true, desc = "Concat", for = "windows" },
]
transcode_media = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-ffmpeg-transcode.py %s', block = true, desc = "Transcode", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-ffmpeg-transcode.py" %s', block = true, desc = "Transcode", for = "windows" },
]
split_media = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-ffmpeg-split.py %s1', block = true, desc = "Split", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-ffmpeg-split.py" %s1', block = true, desc = "Split", for = "windows" },
]
reorder_subs = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-ffmpeg-subtitle.py %s', block = true, desc = "Reorder subs", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-ffmpeg-subtitle.py" %s', block = true, desc = "Reorder subs", for = "windows" },
]
reorder_audio = [
  { run = 'python3 -u ~/.local/scripts/py/yazi-ffmpeg-audio.py %s', block = true, desc = "Reorder audio", for = "unix" },
  { run = 'python -u "%USERPROFILE%\.local\scripts\py\yazi-ffmpeg-audio.py" %s', block = true, desc = "Reorder audio", for = "windows" },
]

[open]
rules = [
  { mime = "text/*", use = [ "edit" ] },
  { mime = "image/*", use = [ "open" ] },
  { mime = "{audio,video}/*", use = [
    "play", "open", "concat_media", "split_media", "transcode_media", "reorder_subs", "reorder_audio",
  ] },
  { mime = "application/{,g}zip", use = [ "extract", "open" ] },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "open" ] },
  { mime = "*", use = [ "open", "edit", "compress_7z", "compress_zip" ] },
]
